# Generated by Django 4.1.4 on 2023-06-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products')),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=255)),
            ],
        ),
    ]
