# Generated by Django 4.1.4 on 2023-06-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_productinbasket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='user_note',
        ),
    ]
