# Generated by Django 4.1.4 on 2023-06-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_alter_productinbasket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
