# Generated by Django 4.1.4 on 2023-06-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_alter_productinbasket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='amount',
            field=models.IntegerField(default='1'),
        ),
    ]
