# Generated by Django 4.1.4 on 2023-06-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_productinbasket_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
