# Generated by Django 4.1.4 on 2023-06-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_productinbasket_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='products_price',
            field=models.IntegerField(default=0),
        ),
    ]
