# Generated by Django 4.1.4 on 2023-06-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_alter_productinbasket_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='products_price',
        ),
    ]
