# Generated by Django 4.1.4 on 2023-06-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_remove_productinbasket_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='products_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
